version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: chore
    labels:
      - dependencies
      - ci

  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: chore
    labels:
      - dependencies
    groups:
      pytest:
        patterns:
          - pytest*
      ruff:
        patterns:
          - ruff*
      sdk:
        patterns:
          - openai
          - anthropic

  - package-ecosystem: pip
    directory: /packages/netllm-sdk-openai
    schedule:
      interval: weekly
    commit-message:
      prefix: chore
    labels:
      - dependencies
      - sdk-bump
    groups:
      sdk:
        patterns:
          - openai
          - anthropic

  - package-ecosystem: pip
    directory: /packages/netllm-sdk-anthropic
    schedule:
      interval: weekly
    commit-message:
      prefix: chore
    labels:
      - dependencies
      - sdk-bump
    groups:
      sdk:
        patterns:
          - openai
          - anthropic
