#!/usr/bin/env python3
"""Generate tests/contract/routes.json — the exact HTTP route surface.

DO NOT EDIT routes.json by hand — regenerate with:

    uv run python scripts/generate-routes-json.py

``--check`` (wired into ``scripts/ci.sh lint``) fails if the checked-in file
has drifted from what ``create_app()`` actually registers.

Why exact-set and not presence: ``test_contract.EXPECTED_HTTP_ROUTES`` listed
17 of ~28 routes and asserted only that each was *present*, so deleting
``/v1/responses`` was CI-green (docs/extending/PROGRAM.md §2, item 0b.4). The
compatibility promise for ``/v1/*`` is "additive only, no sunset", and that
promise is only worth as much as the gate behind it — which has to notice a
removal, not just an addition.

FastAPI's own documentation endpoints are excluded: they are a function of the
installed FastAPI version, not of this repo's contract.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "tests/contract/routes.json"

# Registered by FastAPI itself, versioned with FastAPI, not part of our surface.
FRAMEWORK_PATHS = frozenset(
    {"/docs", "/docs/oauth2-redirect", "/redoc", "/openapi.json"}
)


def collect() -> dict[str, object]:
    from netllm_agent.app import create_app

    app = create_app()
    routes: list[dict[str, object]] = []
    for route in app.routes:
        path = getattr(route, "path", None)
        if path is None or path in FRAMEWORK_PATHS:
            continue
        methods = sorted(getattr(route, "methods", None) or [])
        routes.append({"path": path, "methods": methods})
    routes.sort(key=lambda row: (row["path"], row["methods"]))
    return {
        "_comment": (
            "Generated by scripts/generate-routes-json.py — do not edit by hand. "
            "Asserted as an exact set by tests/test_contract.py."
        ),
        "routes": routes,
    }


def render(payload: dict[str, object]) -> str:
    return json.dumps(payload, indent=2, sort_keys=False) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail instead of writing when the checked-in file is stale",
    )
    args = parser.parse_args()

    payload = collect()
    rendered = render(payload)
    if args.check:
        current = OUT.read_text(encoding="utf-8") if OUT.is_file() else ""
        if current != rendered:
            print(
                "generate-routes-json: tests/contract/routes.json is stale.\n"
                "  A route was added or removed. If that is intended, "
                "regenerate:\n"
                "    uv run python scripts/generate-routes-json.py\n"
                "  Removing a /v1/* route breaks the additive-only promise "
                "this file exists to keep — say so in the PR.",
                file=sys.stderr,
            )
            return 1
        print(f"OK: routes.json up to date ({len(payload['routes'])} routes)")
        return 0

    OUT.write_text(rendered, encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
