#!/usr/bin/env python3
"""Generate dashboard-tokens.css from apps/netllm-mac/design-tokens.json."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
TOKENS_JSON = ROOT / "apps" / "netllm-mac" / "design-tokens.json"
OUTPUT_CSS = (
    ROOT
    / "packages"
    / "netllm-agent"
    / "src"
    / "netllm_agent"
    / "static"
    / "dashboard-tokens.css"
)

HEADER = """/* Generated by scripts/generate-dashboard-tokens.py — do not edit. */
/* Source: apps/netllm-mac/design-tokens.json */
"""


# Token names whose CSS custom property is not the plain kebab-case of the
# JSON key. Kept so existing stylesheets and the macOS app keep resolving.
CSS_NAME_ALIASES = {
    "sidebarWidth": "sidebar-w",
    "monoFont": "mono",
}


def css_name(token: str) -> str:
    """camelCase JSON key -> --kebab-case CSS custom property name."""
    if token in CSS_NAME_ALIASES:
        return CSS_NAME_ALIASES[token]
    out: list[str] = []
    for char in token:
        if char.isupper():
            out.append("-")
            out.append(char.lower())
        else:
            out.append(char)
    return "".join(out)


def css_vars(mode: dict[str, str], shared: dict[str, str]) -> str:
    """Emit every token: mode-specific first, then shared.

    Adding a token to design-tokens.json is all that is needed — no edit here.
    A mode key of the same name wins over a shared key.
    """
    lines = [f"  --{css_name(key)}: {value};" for key, value in mode.items()]
    lines += [
        f"  --{css_name(key)}: {value};"
        for key, value in shared.items()
        if key not in mode
    ]
    return "\n".join(lines)


def render_css(data: dict) -> str:
    """Three layers: system default, OS preference, explicit user override.

    ``:root[data-theme="…"]`` wins over the media query so the Preferences
    theme control can pin a mode regardless of the OS setting.
    """
    shared = data["shared"]
    light = css_vars(data["light"], shared)
    dark = css_vars(data["dark"], shared)
    return (
        HEADER
        + ":root {\n  color-scheme: light dark;\n"
        + light
        + "\n}\n\n@media (prefers-color-scheme: dark) {\n  :root {\n"
        + dark
        + "\n  }\n}\n\n"
        + ':root[data-theme="light"] {\n  color-scheme: light;\n'
        + light
        + "\n}\n\n"
        + ':root[data-theme="dark"] {\n  color-scheme: dark;\n'
        + dark
        + "\n}\n"
    )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit 1 if dashboard-tokens.css is out of date",
    )
    args = parser.parse_args()

    data = json.loads(TOKENS_JSON.read_text(encoding="utf-8"))
    rendered = render_css(data)

    if args.check:
        if not OUTPUT_CSS.is_file():
            print(f"error: missing {OUTPUT_CSS}", file=sys.stderr)
            return 1
        current = OUTPUT_CSS.read_text(encoding="utf-8")
        if current != rendered:
            print(
                "error: dashboard-tokens.css is stale — run: "
                "python scripts/generate-dashboard-tokens.py",
                file=sys.stderr,
            )
            return 1
        return 0

    OUTPUT_CSS.write_text(rendered, encoding="utf-8")
    print(f"wrote {OUTPUT_CSS.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
