#!/usr/bin/env python3
"""Generate dashboard-tokens.css from apps/netllm-mac/design-tokens.json."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
TOKENS_JSON = ROOT / "apps" / "netllm-mac" / "design-tokens.json"
OUTPUT_CSS = (
    ROOT
    / "packages"
    / "netllm-agent"
    / "src"
    / "netllm_agent"
    / "static"
    / "dashboard-tokens.css"
)

HEADER = """/* Generated by scripts/generate-dashboard-tokens.py — do not edit. */
/* Source: apps/netllm-mac/design-tokens.json */
"""


def css_vars(mode: dict[str, str], shared: dict[str, str]) -> str:
    lines = [
        f"  --bg: {mode['bg']};",
        f"  --surface: {mode['surface']};",
        f"  --card: {mode['card']};",
        f"  --border: {mode['border']};",
        f"  --text: {mode['text']};",
        f"  --muted: {mode['muted']};",
        f"  --accent: {mode['accent']};",
        f"  --accent-hover: {mode['accentHover']};",
        f"  --ok: {shared['ok']};",
        f"  --warn: {shared['warn']};",
        f"  --danger: {shared['danger']};",
        f"  --pp-color: {shared.get('ppColor', '#0a84ff')};",
        f"  --tg-color: {shared.get('tgColor', '#34c759')};",
        f"  --ecore-color: {shared.get('ecoreColor', '#ff9500')};",
        f"  --pcore-color: {shared.get('pcoreColor', '#0a84ff')};",
        f"  --code-bg: {mode['codeBg']};",
        f"  --input-bg: {mode['inputBg']};",
        f"  --sidebar-w: {shared['sidebarWidth']};",
        f"  --mono: {shared['monoFont']};",
        f"  --radius: {shared['radius']};",
        f"  --shadow: {mode['shadow']};",
    ]
    return "\n".join(lines)


def render_css(data: dict) -> str:
    shared = data["shared"]
    light = data["light"]
    dark = data["dark"]
    return (
        HEADER
        + ":root {\n  color-scheme: light dark;\n"
        + css_vars(light, shared)
        + "\n}\n\n@media (prefers-color-scheme: dark) {\n  :root {\n"
        + css_vars(dark, shared)
        + "\n  }\n}\n"
    )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit 1 if dashboard-tokens.css is out of date",
    )
    args = parser.parse_args()

    data = json.loads(TOKENS_JSON.read_text(encoding="utf-8"))
    rendered = render_css(data)

    if args.check:
        if not OUTPUT_CSS.is_file():
            print(f"error: missing {OUTPUT_CSS}", file=sys.stderr)
            return 1
        current = OUTPUT_CSS.read_text(encoding="utf-8")
        if current != rendered:
            print(
                "error: dashboard-tokens.css is stale — run: "
                "python scripts/generate-dashboard-tokens.py",
                file=sys.stderr,
            )
            return 1
        return 0

    OUTPUT_CSS.write_text(rendered, encoding="utf-8")
    print(f"wrote {OUTPUT_CSS.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
