#!/usr/bin/env python3
"""Generate DesignTokens.swift from apps/netllm-mac/design-tokens.json.

The twin of generate-dashboard-tokens.py: the macOS app and the web dashboard
resolve the same token names from the same JSON, so a colour can never drift
between the two surfaces. Every colour is emitted as a dynamic NSColor that
resolves per appearance, giving the app real light/dark parity rather than one
hardcoded palette.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
TOKENS_JSON = ROOT / "apps" / "netllm-mac" / "design-tokens.json"
OUTPUT_SWIFT = (
    ROOT / "apps" / "netllm-mac" / "Sources" / "Config" / "DesignTokens.swift"
)

HEADER = """// Generated by scripts/generate-swift-tokens.py — do not edit.
// Source: apps/netllm-mac/design-tokens.json
"""

# Tokens that are lengths, not colours. Emitted as CGFloat.
LENGTH_TOKENS = {"sidebarWidth", "railWidth", "radius", "radiusSm", "radiusLg"}
# Tokens that are neither colour nor length — skipped (CSS-only).
SKIP_TOKENS = {"monoFont", "shadow"}

RGBA_RE = re.compile(
    r"rgba?\(\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*(?:,\s*([\d.]+)\s*)?\)"
)


def parse_color(value: str) -> tuple[float, float, float, float]:
    """'#rrggbb' or 'rgba(r, g, b, a)' -> (r, g, b, a) in 0..1."""
    text = value.strip()
    if text.startswith("#"):
        hexpart = text[1:]
        if len(hexpart) == 3:
            hexpart = "".join(c * 2 for c in hexpart)
        if len(hexpart) != 6:
            raise ValueError(f"unsupported hex colour: {value!r}")
        r, g, b = (int(hexpart[i : i + 2], 16) / 255 for i in (0, 2, 4))
        return (r, g, b, 1.0)
    match = RGBA_RE.fullmatch(text)
    if not match:
        raise ValueError(f"unsupported colour: {value!r}")
    r, g, b = (int(match.group(i)) / 255 for i in (1, 2, 3))
    alpha = float(match.group(4)) if match.group(4) is not None else 1.0
    return (r, g, b, alpha)


def parse_length(value: str) -> float:
    text = value.strip()
    if not text.endswith("px"):
        raise ValueError(f"expected a px length, got {value!r}")
    return float(text[:-2])


def swift_name(token: str) -> str:
    """JSON key -> Swift property name (already lowerCamelCase)."""
    return token


def nscolor_literal(value: str) -> str:
    r, g, b, a = parse_color(value)
    return f"NSColor(srgbRed: {r:.6f}, green: {g:.6f}, blue: {b:.6f}, alpha: {a:.6f})"


def render_swift(data: dict) -> str:
    shared: dict[str, str] = data["shared"]
    light: dict[str, str] = data["light"]
    dark: dict[str, str] = data["dark"]

    lines: list[str] = [
        HEADER,
        "import AppKit",
        "import CoreGraphics",
        "import SwiftUI",
        "",
        "/// Shared visual tokens for the menubar app and web dashboard.",
        "/// Colours resolve per appearance, so light and dark stay in step with",
        "/// dashboard-tokens.css without a second palette to maintain.",
        "enum DesignTokens {",
        "    /// An NSColor that picks its value from the active appearance.",
        "    private static func dynamic(light: NSColor, dark: NSColor) -> Color {",
        "        Color(",
        "            nsColor: NSColor(name: nil) { appearance in",
        "                let isDark = appearance.bestMatch(from: [.aqua, .darkAqua])",
        "                    == .darkAqua",
        "                return isDark ? dark : light",
        "            }",
        "        )",
        "    }",
        "",
        "    // MARK: - Layout",
        "",
        "    static let cardPadding: CGFloat = 16",
        "    static let popoverWidth: CGFloat = 360",
    ]

    # Lengths (shared only — no per-mode length tokens today).
    for key in sorted(k for k in shared if k in LENGTH_TOKENS):
        lines.append(
            f"    static let {swift_name(key)}: CGFloat = {parse_length(shared[key]):g}"
        )
    # `cornerRadius` is the long-standing name for the base radius; keep it as
    # an alias so existing views compile unchanged.
    if "radius" in shared:
        lines.append("    static let cornerRadius: CGFloat = radius")

    lines += ["", "    // MARK: - Appearance-aware colours", ""]

    mode_keys = [
        k
        for k in light
        if k not in SKIP_TOKENS and k not in LENGTH_TOKENS and k in dark
    ]
    for key in mode_keys:
        lines.append(
            f"    static let {swift_name(key)} = dynamic("
            f"light: {nscolor_literal(light[key])}, "
            f"dark: {nscolor_literal(dark[key])})"
        )

    lines += ["", "    // MARK: - Shared colours", ""]
    for key, value in shared.items():
        if key in SKIP_TOKENS or key in LENGTH_TOKENS:
            continue
        r, g, b, a = parse_color(value)
        lines.append(
            f"    static let {swift_name(key)} = Color("
            f"red: {r:.6f}, green: {g:.6f}, blue: {b:.6f}).opacity({a:.6f})"
        )

    lines += [
        "",
        "    // MARK: - Compatibility",
        "",
        "    /// Pre-token call sites; `accent` follows the token, not the system",
        "    /// accent colour, so the two surfaces cannot diverge.",
        f"    static let accentLight = Color({_swift_rgb(light['accent'])})",
        f"    static let accentDark = Color({_swift_rgb(dark['accent'])})",
        "",
        "    static func cardStroke(opacity: Double = 0.06) -> some ShapeStyle {",
        "        Color.primary.opacity(opacity)",
        "    }",
        "}",
        "",
    ]
    return "\n".join(lines)


def _swift_rgb(value: str) -> str:
    r, g, b, _ = parse_color(value)
    return f"red: {r:.6f}, green: {g:.6f}, blue: {b:.6f}"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit 1 if DesignTokens.swift is out of date",
    )
    args = parser.parse_args()

    data = json.loads(TOKENS_JSON.read_text(encoding="utf-8"))
    rendered = render_swift(data)

    if args.check:
        if not OUTPUT_SWIFT.is_file():
            print(f"error: missing {OUTPUT_SWIFT}", file=sys.stderr)
            return 1
        if OUTPUT_SWIFT.read_text(encoding="utf-8") != rendered:
            print(
                "error: DesignTokens.swift is stale — run: "
                "python scripts/generate-swift-tokens.py",
                file=sys.stderr,
            )
            return 1
        return 0

    OUTPUT_SWIFT.write_text(rendered, encoding="utf-8")
    print(f"wrote {OUTPUT_SWIFT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
