// Generated by scripts/generate-swift-tokens.py — do not edit.
// Source: apps/netllm-mac/design-tokens.json

import AppKit
import CoreGraphics
import SwiftUI

/// Shared visual tokens for the menubar app and web dashboard.
/// Colours resolve per appearance, so light and dark stay in step with
/// dashboard-tokens.css without a second palette to maintain.
enum DesignTokens {
    /// An NSColor that picks its value from the active appearance.
    private static func dynamic(light: NSColor, dark: NSColor) -> Color {
        Color(
            nsColor: NSColor(name: nil) { appearance in
                let isDark = appearance.bestMatch(from: [.aqua, .darkAqua])
                    == .darkAqua
                return isDark ? dark : light
            }
        )
    }

    // MARK: - Layout

    static let cardPadding: CGFloat = 16
    static let popoverWidth: CGFloat = 360
    static let radius: CGFloat = 10
    static let radiusLg: CGFloat = 12
    static let radiusSm: CGFloat = 6
    static let railWidth: CGFloat = 170
    static let sidebarWidth: CGFloat = 210
    static let cornerRadius: CGFloat = radius

    // MARK: - Appearance-aware colours

    static let bg = dynamic(light: NSColor(srgbRed: 0.925490, green: 0.925490, blue: 0.925490, alpha: 1.000000), dark: NSColor(srgbRed: 0.109804, green: 0.109804, blue: 0.117647, alpha: 1.000000))
    static let surface = dynamic(light: NSColor(srgbRed: 0.960784, green: 0.960784, blue: 0.968627, alpha: 1.000000), dark: NSColor(srgbRed: 0.172549, green: 0.172549, blue: 0.180392, alpha: 1.000000))
    static let card = dynamic(light: NSColor(srgbRed: 1.000000, green: 1.000000, blue: 1.000000, alpha: 1.000000), dark: NSColor(srgbRed: 0.227451, green: 0.227451, blue: 0.235294, alpha: 1.000000))
    static let panel = dynamic(light: NSColor(srgbRed: 1.000000, green: 1.000000, blue: 1.000000, alpha: 1.000000), dark: NSColor(srgbRed: 0.172549, green: 0.172549, blue: 0.180392, alpha: 1.000000))
    static let inset = dynamic(light: NSColor(srgbRed: 0.960784, green: 0.960784, blue: 0.968627, alpha: 1.000000), dark: NSColor(srgbRed: 0.227451, green: 0.227451, blue: 0.235294, alpha: 1.000000))
    static let border = dynamic(light: NSColor(srgbRed: 0.000000, green: 0.000000, blue: 0.000000, alpha: 0.080000), dark: NSColor(srgbRed: 1.000000, green: 1.000000, blue: 1.000000, alpha: 0.100000))
    static let borderStrong = dynamic(light: NSColor(srgbRed: 0.000000, green: 0.000000, blue: 0.000000, alpha: 0.120000), dark: NSColor(srgbRed: 1.000000, green: 1.000000, blue: 1.000000, alpha: 0.140000))
    static let text = dynamic(light: NSColor(srgbRed: 0.113725, green: 0.113725, blue: 0.121569, alpha: 1.000000), dark: NSColor(srgbRed: 0.960784, green: 0.960784, blue: 0.968627, alpha: 1.000000))
    static let muted = dynamic(light: NSColor(srgbRed: 0.415686, green: 0.415686, blue: 0.435294, alpha: 1.000000), dark: NSColor(srgbRed: 0.643137, green: 0.643137, blue: 0.662745, alpha: 1.000000))
    static let accent = dynamic(light: NSColor(srgbRed: 0.000000, green: 0.478431, blue: 1.000000, alpha: 1.000000), dark: NSColor(srgbRed: 0.039216, green: 0.517647, blue: 1.000000, alpha: 1.000000))
    static let accentSolid = dynamic(light: NSColor(srgbRed: 0.000000, green: 0.443137, blue: 0.929412, alpha: 1.000000), dark: NSColor(srgbRed: 0.000000, green: 0.450980, blue: 0.901961, alpha: 1.000000))
    static let accentHover = dynamic(light: NSColor(srgbRed: 0.000000, green: 0.400000, blue: 0.839216, alpha: 1.000000), dark: NSColor(srgbRed: 0.039216, green: 0.415686, blue: 0.815686, alpha: 1.000000))
    static let accentText = dynamic(light: NSColor(srgbRed: 0.000000, green: 0.372549, blue: 0.776471, alpha: 1.000000), dark: NSColor(srgbRed: 0.427451, green: 0.713725, blue: 1.000000, alpha: 1.000000))
    static let accentTint = dynamic(light: NSColor(srgbRed: 0.000000, green: 0.478431, blue: 1.000000, alpha: 0.100000), dark: NSColor(srgbRed: 0.039216, green: 0.517647, blue: 1.000000, alpha: 0.150000))
    static let okTint = dynamic(light: NSColor(srgbRed: 0.203922, green: 0.780392, blue: 0.349020, alpha: 0.120000), dark: NSColor(srgbRed: 0.203922, green: 0.780392, blue: 0.349020, alpha: 0.150000))
    static let warnTint = dynamic(light: NSColor(srgbRed: 1.000000, green: 0.584314, blue: 0.000000, alpha: 0.120000), dark: NSColor(srgbRed: 1.000000, green: 0.584314, blue: 0.000000, alpha: 0.150000))
    static let dangerTint = dynamic(light: NSColor(srgbRed: 1.000000, green: 0.231373, blue: 0.188235, alpha: 0.120000), dark: NSColor(srgbRed: 1.000000, green: 0.231373, blue: 0.188235, alpha: 0.150000))
    static let okText = dynamic(light: NSColor(srgbRed: 0.090196, green: 0.454902, blue: 0.196078, alpha: 1.000000), dark: NSColor(srgbRed: 0.321569, green: 0.823529, blue: 0.447059, alpha: 1.000000))
    static let warnText = dynamic(light: NSColor(srgbRed: 0.584314, green: 0.333333, blue: 0.000000, alpha: 1.000000), dark: NSColor(srgbRed: 1.000000, green: 0.658824, blue: 0.176471, alpha: 1.000000))
    static let dangerText = dynamic(light: NSColor(srgbRed: 0.694118, green: 0.192157, blue: 0.156863, alpha: 1.000000), dark: NSColor(srgbRed: 1.000000, green: 0.560784, blue: 0.537255, alpha: 1.000000))
    static let gridLine = dynamic(light: NSColor(srgbRed: 0.000000, green: 0.000000, blue: 0.000000, alpha: 0.090000), dark: NSColor(srgbRed: 1.000000, green: 1.000000, blue: 1.000000, alpha: 0.090000))
    static let hoverBg = dynamic(light: NSColor(srgbRed: 0.000000, green: 0.000000, blue: 0.000000, alpha: 0.040000), dark: NSColor(srgbRed: 1.000000, green: 1.000000, blue: 1.000000, alpha: 0.060000))
    static let codeBg = dynamic(light: NSColor(srgbRed: 0.000000, green: 0.000000, blue: 0.000000, alpha: 0.060000), dark: NSColor(srgbRed: 1.000000, green: 1.000000, blue: 1.000000, alpha: 0.100000))
    static let inputBg = dynamic(light: NSColor(srgbRed: 1.000000, green: 1.000000, blue: 1.000000, alpha: 1.000000), dark: NSColor(srgbRed: 0.172549, green: 0.172549, blue: 0.180392, alpha: 1.000000))

    // MARK: - Shared colours

    static let ok = Color(red: 0.203922, green: 0.780392, blue: 0.349020).opacity(1.000000)
    static let warn = Color(red: 1.000000, green: 0.584314, blue: 0.000000).opacity(1.000000)
    static let danger = Color(red: 1.000000, green: 0.231373, blue: 0.188235).opacity(1.000000)
    static let ppColor = Color(red: 0.039216, green: 0.517647, blue: 1.000000).opacity(1.000000)
    static let tgColor = Color(red: 0.203922, green: 0.780392, blue: 0.349020).opacity(1.000000)
    static let ecoreColor = Color(red: 1.000000, green: 0.584314, blue: 0.000000).opacity(1.000000)
    static let pcoreColor = Color(red: 0.039216, green: 0.517647, blue: 1.000000).opacity(1.000000)

    // MARK: - Compatibility

    /// Pre-token call sites; `accent` follows the token, not the system
    /// accent colour, so the two surfaces cannot diverge.
    static let accentLight = Color(red: 0.000000, green: 0.478431, blue: 1.000000)
    static let accentDark = Color(red: 0.039216, green: 0.517647, blue: 1.000000)

    static func cardStroke(opacity: Double = 0.06) -> some ShapeStyle {
        Color.primary.opacity(opacity)
    }
}
