#!/usr/bin/env python3
"""Build venvstacks Python layers for the netllm-mac.app bundle."""

from __future__ import annotations

import argparse
import hashlib
import re
import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PACKAGING = Path(__file__).resolve().parent
TEMPLATE = PACKAGING / "venvstacks.toml"
EXPORT_DIR = PACKAGING / "_export"
BUILD_DIR = PACKAGING / "_build"
FINGERPRINT_FILE = EXPORT_DIR / ".fingerprint"
GENERATED_TOML = PACKAGING / "venvstacks.generated.toml"
REQUIREMENTS_FILE = PACKAGING / "requirements-netllm.txt"

WORKSPACE_PACKAGES = [
    "packages/netllm-core",
    "packages/netllm-sdk-openai",
    "packages/netllm-sdk-anthropic",
    "packages/netllm-discovery",
    "packages/netllm-agent",
    "packages/netllm-cli",
]


def _collect_workspace_requirements() -> list[str]:
    """Gather pinned requirements via uv export."""
    lock = ROOT / "uv.lock"
    if not lock.is_file():
        raise SystemExit("uv.lock not found — run `uv sync` from repo root first")

    result = subprocess.run(
        [
            "uv",
            "export",
            "--no-dev",
            "--no-emit-workspace",
            "--frozen",
            "--no-hashes",
        ],
        cwd=ROOT,
        capture_output=True,
        text=True,
        check=False,
    )
    if result.returncode != 0:
        raise SystemExit(f"uv export failed:\n{result.stderr}")

    pkg_re = re.compile(r"^[a-zA-Z0-9][a-zA-Z0-9._-]*([>=<~!]=|===|@)")
    lines: list[str] = []
    for raw in result.stdout.splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        if pkg_re.match(line):
            lines.append(line)
    return sorted(set(lines))


def _fingerprint_inputs() -> bytes:
    parts: list[bytes] = []
    for rel in ["pyproject.toml", "uv.lock", "packaging/venvstacks.toml"]:
        path = ROOT / rel
        if path.is_file():
            parts.append(path.read_bytes())
    for pkg in WORKSPACE_PACKAGES:
        pyproject = ROOT / pkg / "pyproject.toml"
        if pyproject.is_file():
            parts.append(pyproject.read_bytes())
    return b"\n".join(parts)


def compute_fingerprint() -> str:
    return hashlib.sha256(_fingerprint_inputs()).hexdigest()


def _generate_venvstacks_toml(requirements: list[str]) -> Path:
    template = TEMPLATE.read_text(encoding="utf-8")
    req_block = "\n".join(f'    "{r}",' for r in requirements)
    generated = template.replace(
        "# Populated by build.py — do not hand-edit.\nrequirements = []",
        f"# Generated by build.py\nrequirements = [\n{req_block}\n]",
    )
    GENERATED_TOML.write_text(generated, encoding="utf-8")
    REQUIREMENTS_FILE.write_text("\n".join(requirements) + "\n", encoding="utf-8")
    return GENERATED_TOML


def _python_runner() -> list[str]:
    if shutil.which("uv"):
        return ["uv", "run", "python"]
    return [sys.executable]


def _venvstacks_cmd() -> list[str]:
    return [*_python_runner(), "-m", "venvstacks"]


def _run_venvstacks_export() -> None:
    """Lock, build, and export venvstacks layers (oMLX pipeline)."""
    spec = str(GENERATED_TOML)
    vs = _venvstacks_cmd()

    print("  Locking environments…")
    subprocess.run(
        [*vs, "lock", spec, "--if-needed"],
        cwd=ROOT,
        check=True,
    )

    print("  Building environments…")
    subprocess.run(
        [*vs, "build", spec, "--no-lock"],
        cwd=ROOT,
        check=True,
    )

    if EXPORT_DIR.exists():
        shutil.rmtree(EXPORT_DIR)

    print("  Exporting environments…")
    subprocess.run(
        [*vs, "local-export", spec, "--output-dir", str(EXPORT_DIR)],
        cwd=ROOT,
        check=True,
    )


def build(*, force: bool = False) -> Path:
    fp = compute_fingerprint()
    if (
        not force
        and FINGERPRINT_FILE.is_file()
        and FINGERPRINT_FILE.read_text(encoding="utf-8").strip() == fp
        and EXPORT_DIR.is_dir()
        and any(EXPORT_DIR.iterdir())
    ):
        print(f"venvstacks export up to date (fingerprint {fp[:12]}…)")
        return EXPORT_DIR

    requirements = _collect_workspace_requirements()
    _generate_venvstacks_toml(requirements)
    EXPORT_DIR.mkdir(parents=True, exist_ok=True)
    BUILD_DIR.mkdir(parents=True, exist_ok=True)
    print(f"Exporting venvstacks layers ({len(requirements)} requirements)…")
    _run_venvstacks_export()
    FINGERPRINT_FILE.write_text(fp + "\n", encoding="utf-8")
    print(f"Export complete → {EXPORT_DIR}")
    return EXPORT_DIR


def main() -> None:
    parser = argparse.ArgumentParser(description="Build netllm venvstacks layers")
    parser.add_argument(
        "--venvstacks-only",
        action="store_true",
        help="Export venvstacks layers only",
    )
    parser.add_argument(
        "--print-fingerprint",
        action="store_true",
        help="Print build fingerprint and exit",
    )
    parser.add_argument("--force", action="store_true", help="Ignore fingerprint cache")
    args = parser.parse_args()

    if args.print_fingerprint:
        print(compute_fingerprint())
        return

    if args.venvstacks_only or not args.print_fingerprint:
        build(force=args.force)


if __name__ == "__main__":
    main()
